on: [workflow_dispatch]

name: check

jobs:
  check:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} R ${{ matrix.r-version }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        r-version: [ devel ]

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}

      - uses: s-u/R-actions/tinytex@v1
        with:
          flavor: TinyTeX-1

      - uses: s-u/R-actions/pkg-check@v1
        with:
          check-flags: --as-cran
      - name: Create binary
        run: |
          JD=`pwd`
          (cd ../Rlib && tar fcz "$JD/binary.tar.gz" *)
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: binary.tar.gz
          name: develop
          tag_name: develop
